# Generated by Django 3.2.16 on 2022-12-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Health_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=100)),
                ('password', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'Doctor',
            },
        ),
        migrations.CreateModel(
            name='Medical_Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=100)),
                ('password', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'Medical_Store',
            },
        ),
        migrations.CreateModel(
            name='Patient_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=None, max_length=100)),
                ('Age', models.CharField(default=None, max_length=100)),
                ('Gender', models.CharField(default=None, max_length=100)),
                ('Phone', models.CharField(default=None, max_length=100)),
                ('Address', models.CharField(default=None, max_length=100)),
                ('Medication', models.CharField(default=None, max_length=100)),
                ('Username', models.CharField(default=None, max_length=100)),
                ('Password', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'Patient_Details',
            },
        ),
    ]
