# Generated by Django 3.2.16 on 2022-12-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Health_App', '0003_alter_patient_details_medication'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Address',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Age',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Gender',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Phone',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Speciality',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
