# Generated by Django 3.2.16 on 2022-12-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Health_App', '0004_auto_20221210_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_details',
            name='RFID',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
