# Generated by Django 3.2.16 on 2022-12-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Health_App', '0005_patient_details_rfid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RFID', models.CharField(default=None, max_length=100)),
                ('Medicine', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'Medicine',
            },
        ),
    ]
