# Generated by Django 3.2.16 on 2022-12-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Health_App', '0006_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical_store',
            name='Address',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='medical_store',
            name='Close',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='medical_store',
            name='Name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='medical_store',
            name='Open',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='medicine',
            name='Patient_Id',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
