# Generated by Django 3.2.16 on 2022-12-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Health_App', '0007_auto_20221219_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_details',
            name='Medical',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient_details',
            name='Treatment',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
