# Generated by Django 3.2.16 on 2022-12-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Health_App', '0008_auto_20221219_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_Id', models.CharField(default=None, max_length=100, null=True)),
                ('RFID', models.CharField(default=None, max_length=100)),
                ('Treatment_For', models.CharField(default=None, max_length=100)),
                ('Treatment_Duration', models.CharField(default=None, max_length=100)),
                ('Treatment_Description', models.CharField(default=None, max_length=500)),
            ],
            options={
                'db_table': 'Treatment',
            },
        ),
    ]
