# Generated by Django 3.2.16 on 2022-12-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Health_App', '0009_treatment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medical_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_Id', models.CharField(default=None, max_length=100, null=True)),
                ('RFID', models.CharField(default=None, max_length=100)),
                ('BP', models.CharField(default=None, max_length=100)),
                ('Weight', models.CharField(default=None, max_length=100)),
                ('Height', models.CharField(default=None, max_length=100)),
                ('Past', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'Medical_Details',
            },
        ),
    ]
