# Generated by Django 3.2.16 on 2022-12-19 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Health_App', '0010_medical_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='Medicine',
            new_name='medicine',
        ),
    ]
